# Usa una imagen ligera de Nginx
FROM nginx:alpine

# Copia tu dashboard al directorio público de Nginx
COPY . /usr/share/nginx/html

# Expone el puerto 80 (HTTP)
EXPOSE 80

# Inicia Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
